
[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10

[font.normal]
family = "JetBrainsMono NFP"
style = "Regular"

[window]
opacity = 0.9

[general]
import = ["/home/mmorariu/.config/alacritty/themes/blood-moon.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
