theme = "slick"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "battery"
interval = 10
show = "both"

[[block]]
block = "weather"
format = "{location}  {temp}°C"
service = { name = "openweathermap", api_key = "f6e51446b17c5dd5200a424876a03550", city_id = "1850144", units = "metric" }

[[block]]
block = "weather"
format = "{location}  {temp}°C"
service = { name = "openweathermap", api_key = "f6e51446b17c5dd5200a424876a03550", city_id = "683506", units = "metric" }

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
