#!/bin/sh

[ "$1" == "work" ] && xrandr --output eDP-1 --auto --output DP-1 --mode 2560x1440 --left-of eDP-1
[ "$1" == "home" ] && xrandr --output eDP-1 --auto --output DP-1 --auto --left-of eDP-1
[ "$1" == "auto" ] && xrandr --auto

dwall -s island
