#!/usr/bin/bash

bumblebee-status -t dracula-powerline \
                 -m weather \
                    battery \
                    cpu \
                    memory \
                    sensors2 \
                    aerlive \
                    amixer \
                    datetime \
