#!/usr/bin/bash

bumblebee-status -t gruvbox-powerline-light \
                 -m weather \
                    publicip \
                    battery \
                    cpu \
                    memory \
                    sensors2 \
                    amixer \
                    datetime \
