theme = "slick"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "battery"
interval = 60
show = "percentage"

[[block]]
block = "weather"
format = "{location}  {weather}  {temp}°C"
service = { name = "openweathermap", api_key = "f6e51446b17c5dd5200a424876a03550", city_id = "1850144", units = "metric" }

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
