theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
interval = 5

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "nvidia_gpu"
show_memory = false
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°"

[[block]]
block = "weather"
format = "{location}  {weather}  {temp}°C"
service = { name = "openweathermap", api_key = "f6e51446b17c5dd5200a424876a03550", city_id = "1850144", units = "metric" }

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"

[[block]]
block = "battery"
interval = 60
show = "percentage"
